### ISSUE TITLE
Error after running

### ISSUE THREAD

**Issue by agahEbrahimi** [orbitdb/orbit-core#10]
Hello,
I tried running the script on the readme after installing the modules with node, but this error came up:
```
/Users/behrad/Desktop/Test/node_modules/node-localstorage/LocalStorage.js:160
            throw e;
            ^

Error: ENOENT: no such file or directory, mkdir '/Users/behrad/Desktop/Test/orbit/keys'
    at Object.fs.mkdirSync (fs.js:895:18)
    at LocalStorage._init (/Users/behrad/Desktop/Test/node_modules/node-localstorage/LocalStorage.js:156:14)
    at new LocalStorage (/Users/behrad/Desktop/Test/node_modules/node-localstorage/LocalStorage.js:121:12)
    at Function.useKeyStore (/Users/behrad/Desktop/Test/node_modules/orbit-crypto/index.js:21:18)
    at new Orbit (/Users/behrad/Desktop/Test/node_modules/orbit_/src/Orbit.js:40:12)
    at Object.<anonymous> (/Users/behrad/Desktop/Test/test.js:9:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```
I tracked it with the console and it seems to be generating from the line 
`const orbit = new Orbit(ipfs)`
I'm not sure exactly what to do to fix it, I would appreciate the help. 
Thank you

**Comment by patrick-ogrady** [comment]
Any solution?

**Comment by latenssi** [comment]
This is now fixed in current master
