### ISSUE TITLE
getting TypeError: "listener" argument must be a function on orbit.join()

### ISSUE THREAD

**Issue by otmezger** [orbitdb/orbit-core#11]
Hi, I'm following the example on the readme page of this repository and having my very first interactions with orbit and ipfs. 

I manage to start the ipfs deamon with the command `jsipfs init` and `jsipfs daemon`.

This is my script:

```
/* NOTE! To run this example, you need to have an IPFS daemon running */

'use strict'

const IpfsApi = require('ipfs-api')
const Orbit = require('orbit_')

//const ipfs = IpfsApi()
const ipfs = IpfsApi('/ip4/127.0.0.1/tcp/5002')

const orbit = new Orbit(ipfs)

const username = 'username'

const channel = 'HelloWorld'

orbit.events.on('connected', (network) => {
  //console.log(`-!- Connected to ${network.name}`)
  console.log(`Connected to ${network.name} as ${orbit.user.name}`)
  //orbit.join(channel)
})

orbit.events.on('joined', (channel) => {
  orbit.send(channel, "/me is now caching this channel")
  console.log(`-!- Joined #${channel}`)
})

// Listen for new messages
orbit.events.on('message', (channel, post) => {
  console.log(`[${post.meta.ts}] < ${post.meta.from.name}> ${post.content}`)
})

```

however, when I call `orbit.join(channel)`, I get this error: 

```

TypeError: "listener" argument must be a function
    at _addListener (events.js:239:11)
    at EventEmitter.addListener (events.js:297:10)
    at subscribe (/Users/olmo/sandobx/chat/orbit_based/node_modules/ipfs-api/src/pubsub.js:138:8)
    at Object.subscribe (/Users/olmo/sandobx/chat/orbit_based/node_modules/ipfs-api/src/pubsub.js:58:7)
    at IPFSPubsub.subscribe (/Users/olmo/sandobx/chat/orbit_based/node_modules/orbit-db-pubsub/src/ipfs-pubsub.js:23:27)
    at OrbitDB._createStore (/Users/olmo/sandobx/chat/orbit_based/node_modules/orbit-db/src/OrbitDB.js:71:20)
    at OrbitDB.eventlog (/Users/olmo/sandobx/chat/orbit_based/node_modules/orbit-db/src/OrbitDB.js:29:17)
    at Orbit.join (/Users/olmo/sandobx/chat/orbit_based/node_modules/orbit_/src/Orbit.js:125:27)
```

any help is highly appreciated. 

thanks.

**Comment by latenssi** [comment]
This is now fixed in current master
