### ISSUE TITLE
erro when running tests

### ISSUE THREAD

**Issue by block55** [orbitdb/orbit-core#15]
Hi

When running npm test I get
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/home/user/orbit-core/orbit-core/node_modules/wrtc/build/wrtc/v0.0.61/Release/node-v64-linux-x64/wrtc.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/user/orbit-core/orbit-core/node_modules/wrtc/lib/peerconnection.js:6:15)

**Comment by JaniAnttonen** [comment]
Going to get fixed in #16

**Comment by latenssi** [comment]
This is now fixed in current master
