### ISSUE TITLE
test failure

### ISSUE THREAD

**Issue by whyrusleeping** [orbitdb/orbit-core#2]
```
> orbit_@0.1.0-beta.1 test /home/whyrusleeping/code/orbit-core
> LOG=none ./node_modules/.bin/mocha



  Orbit with js-ipfs-api
    constructor
      ✓ creates an instance
      ✓ creates an instance with options
    connect
      ✓ connects to a network
{ AssertionError: 'QmfM5YmnSGBkLjramPvFSvbCuKqnagVtmGb4yXanPPntbu' == 'QmXWWRTZzygRCnWP8sBcTuygreYBTaQR73zVpZvyxeuUqA'
    at EventEmitter.orbit.events.on (/home/whyrusleeping/code/orbit-core/test/orbit.test.js:94:18)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at IdentityProviders.authorizeUser.then.then.then.then (/home/whyrusleeping/code/orbit-core/src/Orbit.js:85:21)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
  name: 'AssertionError',
  actual: 'QmfM5YmnSGBkLjramPvFSvbCuKqnagVtmGb4yXanPPntbu',
  expected: 'QmXWWRTZzygRCnWP8sBcTuygreYBTaQR73zVpZvyxeuUqA',
  operator: '==',
  message: '\'QmfM5YmnSGBkLjramPvFSvbCuKqnagVtmGb4yXanPPntbu\' == \'QmXWWRTZzygRCnWP8sBcTuygreYBTaQR73zVpZvyxeuUqA\'',
  generatedMessage: true }
      1) emits 'connected' event when connected to a network


  3 passing (1m)
  1 failing

  1) Orbit with js-ipfs-api connect emits 'connected' event when connected to a network:
     Error: timeout of 60000ms exceeded. Ensure the done() callback is being called in this test.





npm ERR! Linux 4.8.7-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "test"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! orbit_@0.1.0-beta.1 test: `LOG=none ./node_modules/.bin/mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the orbit_@0.1.0-beta.1 test script 'LOG=none ./node_modules/.bin/mocha'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the orbit_ package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     LOG=none ./node_modules/.bin/mocha
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs orbit_
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls orbit_
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/whyrusleeping/code/orbit-core/npm-debug.log
make: *** [Makefile:8: test] Error 1
```

**Comment by haadcode** [comment]
Can you try and run the tests from master now? This should be fixed but let me know if you have any problems.

**Comment by haadcode** [comment]
This have been fixed. Closing.
